language:
  - ruby

cache:
  - bundler
  - yarn

node_js: 9

sudo: false

addons:
  chrome: stable

before_install:
  - cp config/database.example.yml config/database.yml

install:
  - bundle install
  - yarn install
  - rails db:setup

script:
  - bundle exec rubocop
  - bundle exec rails test
