language:
  - ruby

cache:
  - bundler
  - yarn

node_js: 9

sudo: required # required with chrome addon
addons:
  chrome: stable

before_install:
  - cp config/database.example.yml config/database.yml
  - cp config/chexpire.test.yml config/chexpire.yml
  - cp config/secrets.example.yml config/secrets.yml

install:
  - bundle install
  - yarn install
  - rails db:create db:migrate

script:
  - bundle exec rubocop
  - bundle exec rails test NO_COVERAGE=1
  - bundle exec rails test:system NO_COVERAGE=1
