# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

language:
  - ruby
rvm:
  ### Zeitwerk is not fully compatible with < 2.5.4
  ### cf. https://github.com/Evolix/chexpire/pull/104
  - 2.5
  - 2.6

cache:
  - bundler
  - yarn

node_js: 9

sudo: required # required with chrome addon
addons:
  chrome: stable

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE chexpire_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml

  # Test configuration loaded from chexpire.defaults.yml,
  # but chexpire.yml file is required
  - touch config/chexpire.yml

install:
  - bundle install
  - yarn install
  - rails db:create db:migrate
  - rails webpacker:compile

script:
  - bundle exec rubocop
  - bundle exec rails test NO_COVERAGE=1
  - bundle exec rails test:system NO_COVERAGE=1
