default: &default
  mailer_default_from: "from@example.org"
  notifier:
    interval: 0.00
    failure_days: 3

development:
  <<: *default
  host: "chexpire.local"

# test configuration included in file used by CI services
<%= IO.read Rails.root.join("config", "chexpire.test.yml") %>
