test:
  mailer_default_from: "contact@chexpire.org"
  host: "localhost"
  notifier:
    interval: 0.00
    failure_days: 3
  checks_domain:
    interval: 0.00
    long_term: 60
    long_term_frequency: 10
  checks_ssl:
    check_http_path:
    check_http_args:
