default: &default
  mailer_default_from: "from@example.org"
  notifier:
    interval: 0.00
    failure_days: 3
  checks_domain:
    interval: 0.5
    long_term: 60
    long_term_frequency: 10
  checks_ssl:
    check_http_path: # default to check_http in $PATH)
    check_http_args: # array of arguments appended to defaults: -C 0 -H $HOSTNAME.

development:
  <<: *default
  host: "chexpire.local"

production:
  action_mailer_config:
    delivery_method: :sendmail

staging:
  action_mailer_config:
    delivery_method: :sendmail

# test configuration included in file used by CI services
<%= IO.read Rails.root.join("config", "chexpire.test.yml") %>
