#!/bin/sh

# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

set -e
[ -n "$DEBUG" ] && set -x

git branch -f staging
git push --force origin staging

bundle exec cap staging deploy
