# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

staging:
  deploy_to: /var/www/my_app_name
  servers:
    -
      host: staging.example.com
      user: deploy
      roles:
        - app
        - db
        - web

production:
  deploy_to: /var/www/my_app_name
  servers:
    -
      host: www.example.com
      user: deploy
      roles:
        - app
        - db
        - web
